# ### Hyprland ###
# Apps
$terminal = kitty
$browser = flatpak run app.zen_browser.zen
$editor = code
$fileExplorer = nautilus

# Touchpad
$touchpadDisableTyping = true
$touchpadScrollFactor = 0.3
$workspaceSwipeFingers = 4
$gestureFingers = 3
$gestureFingersMore = 4

# Blur
$blurEnabled = true
$blurSpecialWs = true
$blurPopups = true
$blurInputMethods = true
$blurSize = 10
$blurPasses = 2
$blurXray = false

# Shadow
$shadowEnabled = true
$shadowRange = 2
$shadowRenderPower = 3
$shadowColour = rgba($surfaced4)

# Gaps
$workspaceGaps = 10
$windowGapsIn = 5
$windowGapsOut = 20
$singleWindowGapsOut = 20

# Window styling
$windowOpacity = 1.0
$windowInactiveOpacity = 0.8
$windowRounding = 8

$windowBorderSize = 1
$activeWindowBorderColour = rgba($primarye6)
$inactiveWindowBorderColour = rgba($onSurfaceVariant11)

# Misc
$volumeStep = 5  # In percent
$cursorTheme = Bibata-Modern-Ice
$cursorSize = 24
# $cursorTheme = rose-pine-hyprcursor
# $cursorSize = 32
$iconTheme = Gruvbox-Plus-Dark


# ### Keybinds ###
# Workspaces
$kbMoveWinToWs = Super+Alt
$kbMoveWinToWsGroup = Ctrl+Super+Alt
$kbGoToWs = Super
$kbGoToWsGroup = Ctrl+Super
$kbToggleLayout = Super, L

$kbNextWs = Ctrl+Super, right
$kbPrevWs = Ctrl+Super, left

$kbToggleSpecialWs = Super, S

# Window groups
$kbWindowGroupCycleNext = Alt, Tab
$kbWindowGroupCyclePrev = Shift+Alt, Tab
$kbUngroup = Super, U
$kbToggleGroup = Super, Comma

# Window actions
$kbMoveWindow = Super, Z
$kbResizeWindow = Super, X
$kbWindowPip = Super+Alt, Backslash
$kbPinWindow = Super, P
$kbWindowFullscreen = Super, F
$kbWindowBorderedFullscreen = Super+Alt, F
$kbToggleWindowFloating = Super+Alt, Space
$kbCloseWindow = Super, Q

# Special workspace toggles
$kbSystemMonitor = Ctrl+Shift, Escape
$kbMusic = Super, M
$kbCommunication = Super, D
$kbTodo = Super, R

# Apps
$kbTerminal = Super, Return
$kbBrowser = Super, B
$kbEditor = Super, C
$kbFileExplorer = Super, E

# Misc
$kbSession = Ctrl+Alt, Delete
$kbShowNotifs = Super, N
$kbClearNotifs = Ctrl+Alt, C
$kbShowPanels = Super, K
$kbLock = Super, Escape
$kbRestoreLock = Super+Alt, L
