animations {
    enabled = true

    # Animation curves
    bezier = specialWorkSwitch, 0.05, 0.7, 0.1, 1
    bezier = emphasizedAccel, 0.3, 0, 0.8, 0.15
    bezier = emphasizedDecel, 0.05, 0.7, 0.1, 1
    bezier = standard, 0.2, 0, 0, 1
    bezier = md3_decel, 0.05, 0.7, 0.1, 1
    bezier = md3_accel, 0.3, 0, 0.8, 0.15

    # Animation configs
    animation = layersIn, 1, 5, emphasizedDecel, slide
    animation = layersOut, 1, 4, emphasizedAccel, slide
    animation = fadeLayers, 1, 5, standard

    animation = windows, 1, 3, md3_decel, popin 60%
    animation = windowsIn, 1, 3, md3_decel, popin 60%
    animation = windowsOut, 1, 3, md3_accel, popin 60%
    animation = windowsMove, 1, 6, standard
    animation = workspaces, 1, 5, standard

    animation = specialWorkspace, 1, 4, specialWorkSwitch, slidefadevert 15%

    animation = fade, 1, 6, standard
    animation = fadeDim, 1, 6, standard
    animation = border, 1, 6, standard
}
